apiVersion: v1
kind: Pod
metadata:
# nom pod
  name: webserver
  labels:
    env: production
    owner: rahmafrioui
    webserver: nginx
spec:
  containers:
    - name: nginx
      image: nginx:1.24.1
      ports: 
        - containerPort: 80
